version: 2.1
orbs:
  node: circleci/node@1.1.2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Pull submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build homotopy-core
          command: cd homotopy-core && npm install && npm run build
      - run:
          name: Build web client
          command: npm run build
      - save_cache:
          key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
            - storage.rules
  deploy:
    executor: node/default
    steps:
      - restore_cache:
          key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install firebase-tools
          command: npm install firebase-tools
      - run:
          name: Deploy to firebase
          command: ../node_modules/.bin/firebase deploy --token $FIREBASE_DEPLOY_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: stable
